export const SUBJECTS = [
  'SPLDV',
  'MATRIKS',
  'KALKULUS',
  'ALJABAR',
  'GEOMETRI',
  'TRIGONOMETRI',
  'STATISTIKA',
  'PELUANG',
  'MOSAEC_EVALUATION',
  'LOGARITMA',
  'STATISTIKA BIVARIAT',
  'LINGKARAN',
  // Kelas 10
  'EKSPONEN',
  'BENTUK AKAR',
  'PERSAMAAN EKSPONENSIAL',
  'FUNGSI EKSPONENSIAL',
  'LOGIKA MATEMATIKA',
  'PERTIDAKSAMAAN LINEAR',
  'PERSAMAAN KUADRAT',
  'FUNGSI KUADRAT',
  // Kelas 11
  'BARISAN ARITMETIKA',
  'DERET ARITMETIKA',
  'BARISAN GEOMETRI',
  'DERET GEOMETRI',
  'BUNGA TUNGGAL',
  'BUNGA MAJEMUK',
  'KOMPOSISI FUNGSI',
  'INVERS FUNGSI',
  // Kelas 12
  'TRANSFORMASI FUNGSI',
  'LIMIT FUNGSI',
  'TURUNAN',
  'INTEGRAL',
  'FR 2025 TKA SMA MTK LANJUT',
  'FR 2025 TKA SMA MTK UMUM',
] as const;

export type SubjectType = typeof SUBJECTS[number];

export const GRADE_LEVELS = ['CLASS_10', 'CLASS_11', 'CLASS_12'] as const;
export type GradeLevelType = typeof GRADE_LEVELS[number];
